version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports: 
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DATABASE_URL: "postgres://postgres:example@db:5432/mydb?sslmode=disable"
    ports:
      - "8080:8080"
